language: python
cache: pip
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  # PyPy versions
  - "pypy"
  - "pypy3"
# command to install dependencies
before_install:
  - "pip install -U pytest"
install:
 - "pip install -U py==1.4.29"
 - "pip install -r requirements.txt"
# command to run tests
script: python setup.py test
